# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 11:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gempabumi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('origin_time', models.TimeField(blank=True)),
                ('lintang', models.FloatField()),
                ('bujur', models.FloatField()),
                ('kedalaman', models.PositiveIntegerField(blank=True, null=True)),
                ('magnitudo', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('terasa', models.BooleanField(default=False)),
                ('pga_z', models.FloatField()),
                ('pga_ns', models.FloatField()),
                ('pga_ew', models.FloatField()),
                ('shakemap', models.BooleanField(default=False)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gempabumi',
                'ordering': ['tanggal'],
            },
        ),
    ]
