# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gempabumi',
            name='pga_ew',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gempabumi',
            name='pga_ns',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gempabumi',
            name='pga_z',
            field=models.FloatField(default=0),
        ),
    ]
