# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operasional', '0002_auto_20160728_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListrikUdara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('stroke', models.IntegerField(blank=True, null=True)),
                ('apm_stroke', models.FloatField(default=0.0)),
                ('strong', models.IntegerField(blank=True, null=True)),
                ('apm_strong', models.FloatField(default=0.0)),
                ('noise', models.IntegerField(blank=True, null=True)),
                ('apm_noise', models.FloatField(default=0.0)),
                ('energy', models.IntegerField(blank=True, null=True)),
                ('apm_energy', models.FloatField(default=0.0)),
                ('stroke_peak', models.PositiveIntegerField(blank=True, null=True)),
                ('time_stroke_peak', models.TimeField(blank=True)),
                ('strong_peak', models.PositiveIntegerField(blank=True, null=True)),
                ('time_strong_peak', models.TimeField(blank=True)),
                ('noise_peak', models.PositiveIntegerField(blank=True, null=True)),
                ('time_noise_peak', models.TimeField(blank=True)),
                ('energy_peak', models.PositiveIntegerField(blank=True, null=True)),
                ('time_energy_peak', models.TimeField(blank=True)),
                ('energy_ratio_peak', models.PositiveIntegerField(blank=True, null=True)),
                ('time_ratio_peak', models.TimeField(blank=True)),
                ('signal_peak', models.PositiveIntegerField(blank=True, null=True)),
                ('time_signal_peak', models.TimeField(blank=True)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Listrik Udara',
                'ordering': ['tanggal'],
            },
        ),
    ]
