# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0003_listrikudara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listrikudara',
            name='apm_stroke',
            field=models.FloatField(default=0.0, verbose_name='average'),
        ),
    ]
