# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0004_auto_20160728_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listrikudara',
            name='apm_energy',
            field=models.FloatField(default=0.0, verbose_name='average'),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='apm_noise',
            field=models.FloatField(default=0.0, verbose_name='average'),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='apm_strong',
            field=models.FloatField(default=0.0, verbose_name='average'),
        ),
    ]
