# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 13:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operasional', '0005_auto_20160728_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hujan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('jumlah', models.FloatField(default=0.0)),
                ('keterangan', models.CharField(blank=True, choices=[('nihil', 'Nihil'), ('sangat ringan', 'Sangat Ringan'), ('ringan', 'ringan'), ('sedang', 'Sedang'), ('lebat', 'Lebat'), ('sangat lebat', 'sangat lebat')], max_length=100)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hujan',
                'ordering': ['tanggal'],
            },
        ),
    ]
