# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0008_laporan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listrikudara',
            name='energy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='energy_peak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='energy_ratio_peak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='noise',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='noise_peak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='signal_peak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='stroke',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='stroke_peak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='strong',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='strong_peak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='time_energy_peak',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='time_noise_peak',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='time_ratio_peak',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='time_signal_peak',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='time_stroke_peak',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='listrikudara',
            name='time_strong_peak',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
    ]
