# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
