# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0002_pegawai_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
