# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 12:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tata_usaha', '0003_auto_20160725_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlatTulisKantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('nama_barang', models.CharField(blank=True, max_length=100)),
                ('jumlah', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Alat Tulis Kantor',
            },
        ),
        migrations.CreateModel(
            name='Diklat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_diklat', models.CharField(blank=True, max_length=100)),
                ('waktu_mulai', models.DateField(default=datetime.datetime.today)),
                ('waktu_berakhir', models.DateField(default=datetime.datetime.today)),
                ('lokasi', models.CharField(blank=True, max_length=100)),
                ('presentasi', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['waktu_mulai', 'nama_diklat'],
                'verbose_name_plural': 'Diklat',
            },
        ),
        migrations.CreateModel(
            name='JadwalDinasSatpam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'tanggal',
            },
        ),
        migrations.CreateModel(
            name='ListrikMati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('jam_mulai', models.TimeField(blank=True)),
                ('jam_berakhir', models.TimeField(blank=True)),
                ('kondisi_bbm', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('petugas_entri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Listrik Mati',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('judul', models.CharField(blank=True, max_length=100)),
                ('dari', models.CharField(blank=True, max_length=100)),
                ('kepada', models.CharField(blank=True, max_length=100)),
                ('isi_memo', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('petugas_entri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Memo',
            },
        ),
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('nomor_surat', models.CharField(blank=True, max_length=100)),
                ('perihal', models.CharField(blank=True, max_length=100)),
                ('tujuan', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('petugas_entri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Surat Keluar',
            },
        ),
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('nomor_surat', models.CharField(blank=True, max_length=100)),
                ('perihal', models.CharField(blank=True, max_length=100)),
                ('dari', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('petugas_entri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Surat Masuk',
            },
        ),
        migrations.CreateModel(
            name='TugasBelajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, choices=[('Diploma 4', 'Diploma 4'), ('Sarjana', 'Sarjana'), ('Magister', 'Magister'), ('Doctoral', 'Doctoral')], max_length=100)),
                ('perguruan_tinggi', models.CharField(blank=True, max_length=200)),
                ('tahun_mulai', models.PositiveIntegerField(blank=True, null=True)),
                ('tahun_lulus', models.PositiveIntegerField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['pegawai'],
                'verbose_name_plural': 'Tugas Belajar',
            },
        ),
        migrations.AlterModelOptions(
            name='divisi',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Divisi'},
        ),
        migrations.AlterModelOptions(
            name='jabatan',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='jenisakun',
            options={'verbose_name_plural': 'Jenis Akun'},
        ),
        migrations.AlterModelOptions(
            name='pegawai',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Pegawai'},
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='agama',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Protestan', 'Protestan'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghuchu', 'Konghuchu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='status',
            field=models.CharField(blank=True, choices=[('PNS', 'PNS'), ('CPNS', 'CPNS'), ('Honor', 'Honor'), ('Magang', 'Magang')], max_length=100),
        ),
        migrations.AddField(
            model_name='tugasbelajar',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata_usaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='tugasbelajar',
            name='petugas_entri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jadwaldinassatpam',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata_usaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='jadwaldinassatpam',
            name='petugas_entri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diklat',
            name='nama_peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata_usaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='diklat',
            name='peetugas_entri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alattuliskantor',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata_usaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='alattuliskantor',
            name='petugas_entri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
