# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0004_auto_20160725_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diklat',
            old_name='peetugas_entri',
            new_name='petugas_entri',
        ),
        migrations.AlterField(
            model_name='diklat',
            name='presentasi',
            field=models.BooleanField(default=False),
        ),
    ]
