# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0005_auto_20160725_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugasbelajar',
            name='jurusan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
