# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0006_tugasbelajar_jurusan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwaldinassatpam',
            options={'ordering': ['tanggal'], 'verbose_name_plural': 'Jadwal Dinas Satpam'},
        ),
    ]
