# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_usaha', '0007_auto_20160728_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaldinassatpam',
            name='keterangan',
            field=models.CharField(blank=True, choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam')], max_length=100),
        ),
    ]
